In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
movie_df = pd.read_csv('movies_metadata.csv')

In [4]:
movie_df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [5]:
movie_df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [6]:
movie_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [7]:
movie_df.shape

(45466, 24)

In [8]:
movie_df.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [9]:
#checking duplicates and then removing them

movie_df.duplicated().sum()

np.int64(13)

In [10]:
movie_df = movie_df.drop_duplicates().reset_index(drop = True)

In [11]:
movie_df.duplicated().sum()

np.int64(0)

In [12]:
movie_df.shape

(45453, 24)

In [13]:
#not all the columns are necessary . So taking only the imp ones

movie_df = movie_df[['title','overview','genres','tagline','belongs_to_collection','vote_average','popularity']]

In [14]:
movie_df

,title,overview,genres,tagline,belongs_to_collection,vote_average,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",NaN,"{'id': 10194, 'name': 'Toy Story Collection', ...",7.7,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",Roll the dice and unleash the excitement!,NaN,6.9,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",Still Yelling. Still Fighting. Still Ready for...,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",6.5,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",Friends are the people who let you be yourself...,NaN,6.1,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,"[{'id': 35, 'name': 'Comedy'}]",Just When His World Is Back To Normal... He's ...,"{'id': 96871, 'name': 'Father of the Bride Col...",5.7,8.387519
...,...,...,...,...,...,...,...
45448,Subdue,Rising and falling between a man and woman.,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",Rising and falling between a man and woman,NaN,4.0,0.072051
45449,Century of Birthing,An artist struggles to finish his work while a...,"[{'id': 18, 'name': 'Drama'}]",NaN,NaN,9.0,0.178241
45450,Betrayal,"When one of her hits goes wrong, a professiona...","[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",A deadly game of wits.,NaN,3.8,0.903007
45451,Satan Triumphant,"In a small town live two brothers, one a minis...",[],NaN,NaN,0.0,0.003503
45452,Queerama,50 years after decriminalisation of homosexual...,[],NaN,NaN,0.0,0.163015

In [15]:
movie_df.isnull().sum()

title                        6
overview                   954
genres                       0
tagline                  25045
belongs_to_collection    40959
vote_average                 6
popularity                   5
dtype: int64

In [16]:
#if data is missing in 'title' column then other columns are of no use like genres , tagline etc . So remove missing values of Title

movie_df = movie_df.dropna(subset = ['title'])

In [17]:
# 'overview' text h toh direct mean median nhi nikal sakte toh usme jo jo khali jagah h uske jagah empty space fill kar do

movie_df['overview'] = movie_df['overview'].fillna('')

In [18]:
movie_df.iloc[0]['genres']

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [19]:
import ast
movie_df['genres'] = movie_df['genres'].apply(lambda x :" ".join([i['name'] for i in ast.literal_eval(x)]))

In [20]:
movie_df.iloc[1]['belongs_to_collection']

nan

In [21]:
# the output is coming like 'genres' column but we only need the value pair for name key
# not similar to 'genres' because in it , it was like many dict in a list which was in a string
# but here it is like single dict in a string

In [22]:
# Convert messy collection data into only collection names
# ast.literal_eval(x)['name'] --> This is for non-missing rows. 1)Converts string → dictionary 2)get name
# pd.notna() means: if value exists → True & if NaN → False . If missing: Return empty string

movie_df['belongs_to_collection'] = movie_df['belongs_to_collection'].apply(lambda x: ast.literal_eval(x)['name'] if pd.notna(x) else '')

In [23]:
movie_df.head()

,title,overview,genres,tagline,belongs_to_collection,vote_average,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,NaN,Toy Story Collection,7.7,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,,6.9,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,Grumpy Old Men Collection,6.5,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,,6.1,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,Father of the Bride Collection,5.7,8.387519

In [24]:
#there are many 'tagline' that are missing so we will simply put an empty string in each of them as we did for 'overview'
movie_df['tagline'] = movie_df['tagline'].fillna('')

In [25]:
movie_df.isnull().sum()

title                    0
overview                 0
genres                   0
tagline                  0
belongs_to_collection    0
vote_average             0
popularity               0
dtype: int64

In [26]:
# jiska jiska 'title' missing tha uska he 'vote_average' aur 'popularity' missing tha kyuki hum toh sirf 'title' drop kiye but wo dono
# automatically drop hogye

In [27]:
# aage jaake 'overview','tagline','genres' jaise text ko numeric values me convert karna h but har column ke liye karne se better h ki ek
# column bana lete h aur usme ye teeno ko store kar lete h aur uska numeric nikal lete h

movie_df['tags'] = (movie_df['title'] + " " + movie_df['overview'] + " " + movie_df['genres'] + " " + movie_df['tagline'] + " " +
movie_df['belongs_to_collection'])

In [28]:
movie_df.head()

,title,overview,genres,tagline,belongs_to_collection,vote_average,popularity,tags
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,,Toy Story Collection,7.7,21.946943,"Toy Story Led by Woody, Andy's toys live happi..."
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,,6.9,17.015539,Jumanji When siblings Judy and Peter discover ...
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,Grumpy Old Men Collection,6.5,11.7129,Grumpier Old Men A family wedding reignites th...
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,,6.1,3.859495,"Waiting to Exhale Cheated on, mistreated and s..."
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,Father of the Bride Collection,5.7,8.387519,Father of the Bride Part II Just when George B...

In [29]:
movie_df['tags'][1]

"Jumanji When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- into their living room. Alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures. Adventure Fantasy Family Roll the dice and unleash the excitement! "

NLP
1. remove stop words and punctuators
2. tokenization - splitting the words
3. using lemmatization

In [30]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [31]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [32]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [33]:
def preprocess_text(text):
  #lowercase
  text = str(text).lower()
  #remove punctuators
  text = re.sub(r'[^a-zA-Z\s]','',text)
  #tokenization
  words = text.split()
  #removing stopwords
  words = [word for word in words if word not in stop_words]
  #lemmatizing
  words = [lemmatizer.lemmatize(word) for word in words]

  return " ".join(words)

In [34]:
movie_df['tags'] = movie_df['tags'].apply(preprocess_text)

In [35]:
movie_df.head()

,title,overview,genres,tagline,belongs_to_collection,vote_average,popularity,tags
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,,Toy Story Collection,7.7,21.946943,toy story led woody andys toy live happily roo...
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,,6.9,17.015539,jumanji sibling judy peter discover enchanted ...
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,Grumpy Old Men Collection,6.5,11.7129,grumpier old men family wedding reignites anci...
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,,6.1,3.859495,waiting exhale cheated mistreated stepped woma...
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,Father of the Bride Collection,5.7,8.387519,father bride part ii george bank recovered dau...

In [36]:
movie_df['tags'][1]

'jumanji sibling judy peter discover enchanted board game open door magical world unwittingly invite alan adult who trapped inside game year living room alans hope freedom finish game prof risky three find running giant rhinoceros evil monkey terrifying creature adventure fantasy family roll dice unleash excitement'

In [37]:
movie_df = movie_df.reset_index(drop = True)

In [38]:
#converts every char to lower and remove if any leading or trailing space is there
movie_df['title_clean'] = movie_df['title'].str.lower().str.strip()

indices =pd.Series(movie_df.index,index = movie_df['title_clean']).drop_duplicates()
indices

title_clean
toy story                          0
jumanji                            1
grumpier old men                   2
waiting to exhale                  3
father of the bride part ii        4
                               ...
subdue                         45442
century of birthing            45443
betrayal                       45444
satan triumphant               45445
queerama                       45446
Length: 45447, dtype: int64

In [39]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [40]:
tfidf = TfidfVectorizer(max_features=50000,ngram_range=(1,2),stop_words = 'english')

In [41]:
tfidf_matrix = tfidf.fit_transform(movie_df['tags'])

In [42]:
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1610357 stored elements and shape (45447, 50000)>

In [43]:
print(tfidf_matrix)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1610357 stored elements and shape (45447, 50000)>
  Coords	Values
  (0, 44996)	0.3303627408058072
  (0, 41895)	0.0966724730157359
  (0, 24489)	0.08623873008871975
  (0, 48967)	0.3864884422575618
  (0, 1430)	0.4267657871766732
  (0, 25662)	0.0681361205488793
  (0, 19536)	0.10654102382529687
  (0, 37395)	0.08583762173013722
  (0, 3915)	0.09891268848017012
  (0, 4944)	0.0852106290278814
  (0, 5375)	0.401447293853353
  (0, 38112)	0.08315644803578988
  (0, 663)	0.10712316510949474
  (0, 26309)	0.09469162777580228
  (0, 33746)	0.0692677651543229
  (0, 19872)	0.07401014908463023
  (0, 33942)	0.08120422034088234
  (0, 6912)	0.09992790119627687
  (0, 38951)	0.10297866283670874
  (0, 32399)	0.08115896656092177
  (0, 12607)	0.10654102382529687
  (0, 13871)	0.08410890494914135
  (0, 24430)	0.0818047404319697
  (0, 2112)	0.11821537790983214
  (0, 11190)	0.10200800975981371
  :	:
  (45445, 12764)	0.129942825624553
  (45445, 25670)	0.14187118562328127
  (45445, 44947)	0.14013865867711853
  (45445, 23791)	0.129942825624553
  (45445, 9216)	0.1438353626763804
  (45446, 49462)	0.11345501643440307
  (45446, 28516)	0.14350216922140915
  (45446, 48665)	0.11262155705037223
  (45446, 15388)	0.17802033701009345
  (45446, 36139)	0.1528840981792522
  (45446, 20718)	0.2769342694106162
  (45446, 11309)	0.16389753683900837
  (45446, 22847)	0.24111485880651087
  (45446, 10859)	0.19587621043888717
  (45446, 17527)	0.20442005300708446
  (45446, 43902)	0.17351544036396338
  (45446, 6155)	0.1772199366810794
  (45446, 43906)	0.1999304142899919
  (45446, 14199)	0.27532120519435294
  (45446, 1813)	0.2541606835967597
  (45446, 28573)	0.24450797187956064
  (45446, 17537)	0.2978144772135333
  (45446, 45925)	0.26695900069242695
  (45446, 9425)	0.2769342694106162
  (45446, 3728)	0.3444079790959214

In [44]:
from sklearn.metrics.pairwise import cosine_similarity

In [45]:
def recommend(title,n=10):
  title = title.lower().strip()

  if title not in indices:
    return ['Movie not found']

  idx = indices[title]
  sim_score = cosine_similarity(tfidf_matrix[idx],tfidf_matrix).flatten()
  similar_idx = sim_score.argsort()[::-1][1:n+1]
  return movie_df['title'].iloc[similar_idx]

In [54]:
recommend("thor")

21932                                 Thor: The Dark World
26553                                       Thor: Ragnarok
38830                                            I Am Thor
41145                                            Team Thor
17491                                        Almighty Thor
20788                                Thor: Tales of Asgard
19524                                             Kon-Tiki
42067    Marvel One-Shot: A Funny Thing Happened on the...
35242           Marvel Super Hero Adventures: Frost Fight!
39969                 Ecstasy of Order: The Tetris Masters
Name: title, dtype: object